swagger: "2.0"
info:
  title: Spotify MCP Server
  description: MCP endpoint exposing Spotify Web API tools
  version: 1.0.0
host: spotify-mcp-hha8cccmgnete3fm.australiaeast-01.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Invoke Spotify MCP
      operationId: InvokeMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Successful MCP response
