swagger: '2.0'
info:
  title: Spotify MCP Server
  description: Model Context Protocol server for Spotify API
  version: 1.0.0
host: spotify-mcp-hha8cccmgnete3fm.australiaeast-01.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Spotify MCP Server
      operationId: InvokeMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      produces:
        - text/event-stream
      consumes:
        - application/json
      responses:
        '200':
          description: OK
