swagger: '2.0'
info:
  title: Spotify MCP Server
  description: MCP server exposing Spotify API tools for Copilot Studio.
  version: 1.0.0
host: spotify-mcp-hha8cccmgnete3fm.australiaeast-01.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Spotify MCP server endpoint
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Success
